#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/inetd,v 1.6.2.1.6.1 2010/12/21 17:09:25 kensmith Exp $
#

# PROVIDE: hv_kvpd
# REQUIRE: DAEMON LOGIN cleanvar devfs

. /etc/rc.subr

name="hv_kvp_daemon"
rcvar=`set_rcvar`
command="/usr/freebsd/sys/dev/hyperv/utilities/${name}"
start_postcmd="/sbin/kldload /usr/freebsd/sys/dev/hyperv/utilities/hv_kvp.ko"
stop_cmd="echo STOP NOT Supported"
required_dirs="/var/opt/hyperv"

load_rc_config $name
run_rc_command "$1"
